language: php

stages:
  # Run tests against unstable Laravel versions for builds triggered by a cron
  - name: Unstable
    if: type = cron
  - Maze Runner

matrix:
  include:
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel56
      stage: Maze Runner
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel58
      stage: Maze Runner
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel66
      stage: Maze Runner

    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION='8.x-dev as 8'
      stage: Unstable
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION='dev-master as 8'
      stage: Unstable
    - addons:
        apt:
          packages:
          - docker-ce
      sudo: required
      sevices:
      - docker
      rvm: 2.4.1
      php: 7.4
      before_install: ruby --version
      install:
        - bundle install
        - ./.ci/setup-laravel-dev-fixture.sh
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel-latest
      stage: Unstable

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  - if [[ $TRAVIS_PHP_VERSION == 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist ; fi
  # Show which versions of our direct dependencies we're using
  - composer show --direct

script:
  - composer test
